version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - bot
    restart: unless-stopped