FROM python:3.13-alpine3.21

WORKDIR /app


COPY bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY bot .

CMD ["python", "-m", "uvicorn", "bot_control:app", "--host", "0.0.0.0", "--port", "8000"]